apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: backend
  name: backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
       app.kubernetes.io/name: backend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: backend
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gs-key
      - name: plynx-secret-key
        secret:
          secretName: secret-key
      - name: plynx-config-volume
        configMap:
          name: plynx-config
      containers:
      - image: plynxteam/plynx-deploy:0.7.1
        name: backend
        command:
          - plynx
          - api
          - "-vvvv"
          - "--db-host"
          - mongo
          - "--storage-scheme"
          - $(STORAGE_SCHEME)
          - "--storage-prefix"
          - $(STORAGE_PREFIX)
          - "--secret-key"
          - $(SECRET_KEY)
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            port: 5000
            path: /health
        imagePullPolicy: Always
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        - name: plynx-config-volume
          mountPath: /etc/plynx-config
        resources:
          requests:
            memory: 512Mi
          limits:
            memory: 512Mi
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret-key
              key: secret.txt
        - name: STORAGE_SCHEME
          valueFrom:
            configMapKeyRef:
              name: storage-config
              key: storage-scheme
        - name: STORAGE_PREFIX
          valueFrom:
            configMapKeyRef:
              name: storage-config
              key: storage-prefix
        - name: PLYNX_CONFIG_PATH
          value: /etc/plynx-config/config.yaml
        - name: KUBECONFIG
          value: /app/kubeconfig.yaml
      restartPolicy: Always
