apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers:
      - image: plynxteam/ui:1.5.3
        name: frontend
        ports:
        - containerPort: 80
        resources: {}
        imagePullPolicy: Always
        resources:
          requests:
            memory: 2048Mi
          limits:
            memory: 2048Mi
      restartPolicy: Always
status: {}
