apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: frontend
  name: frontend
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
       app.kubernetes.io/name: frontend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: frontend
    spec:
      containers:
      - image: plynxteam/ui:1.7.4
        name: frontend
        ports:
        - containerPort: 80
        resources: {}
        imagePullPolicy: Always
        resources:
          requests:
            memory: 2048Mi
          limits:
            memory: 2048Mi
      restartPolicy: Always
status: {}
