apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
       app.kubernetes.io/name: worker
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: worker
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gs-key
      - name: plynx-config-volume
        configMap:
          name: plynx-config
      containers:
      - image: plynxteam/plynx-deploy:0.5.6
        name: worker
        command:
          - plynx
          - worker
          - "-vvvv"
          - "--storage-scheme"
          - $(STORAGE_SCHEME)
          - "--storage-prefix"
          - $(STORAGE_PREFIX)
          - "--db-host"
          - mongo
          - "-e"
          - "basic-bash-jinja2-operation"
          - "-e"
          - "basic-python-node-operation"
          - "-e"
          - "basic-dag-operation"
          - "-e"
          - "basic-dag-workflow"
          - "-e"
          - "k8s-bash-jinja2-operation"
          - "-e"
          - "k8s-python-node-operation"
          - "-e"
          - "python-workflow"
        imagePullPolicy: Always
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        - name: plynx-config-volume
          mountPath: /etc/plynx-config
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: STORAGE_SCHEME
          valueFrom:
            configMapKeyRef:
              name: storage-config
              key: storage-scheme
        - name: STORAGE_PREFIX
          valueFrom:
            configMapKeyRef:
              name: storage-config
              key: storage-prefix
        - name: PLYNX_CONFIG_PATH
          value: /etc/plynx-config/config.yaml
        - name: KUBECONFIG
          value: /app/kubeconfig.yaml
      restartPolicy: Always
