mongodb:
  user:
  password:
  host: 'mongodb'
  port: 27017

storage:
  scheme: gs
  prefix: gs://plynx-prod-bucket/resources/

auth:
  secret_key:

web:
  host: '0.0.0.0'
  port: 5000
  endpoint: https://platform.plynx.com
  debug: true

demo:
  enabled: true
  template_id: 5ee178682ff29bf2266f9f1f
  # kind: python-workflow

plugins:
  resources:
    - kind: file
      title: File
      cls: plynx.plugins.resources.common.File
      icon: feathericons.file
      color: '#fff'
    - kind: pdf
      title: PDF file
      cls: plynx.plugins.resources.common.PDF
      icon: plynx.pdf
    - kind: image
      title: Image
      cls: plynx.plugins.resources.common.Image
      icon: plynx.image
    - kind: csv
      title: CSV file
      cls: plynx.plugins.resources.common.CSV
      icon: plynx.csv
    - kind: tsv
      title: TSV file
      cls: plynx.plugins.resources.common.TSV
      icon: plynx.tsv
    - kind: json
      title: JSON file
      cls: plynx.plugins.resources.common.Json
      icon: plynx.json
    - kind: executable
      title: Executable
      cls: plynx.plugins.resources.common.Executable
      icon: feathericons.play
      color: '#fcff57'
    - kind: directory
      title: Directory
      cls: plynx.plugins.resources.common.Directory
      icon: feathericons.folder
      color: '#f44'
    - kind: cloud-storage
      title: Cloud Storage
      cls: plynx.plugins.resources.cloud_resources.CloudStorage
      icon: feathericons.hard-drive
      color: '#5ed1ff'

    - kind: int
      title: int
      cls: plynx.plugins.resources.common.Raw
      icon: plynx.python-int
    - kind: str
      title: str
      cls: plynx.plugins.resources.common.Raw
      icon: feathericons.type
      color: '#f44'
    - kind: dict
      title: dict
      cls: plynx.plugins.resources.common.Raw
      icon: plynx.json
    - kind: float
      title: float
      cls: plynx.plugins.resources.common.Raw
      icon: plynx.python-float
    - kind: list
      title: list
      cls: plynx.plugins.resources.common.Raw
      icon: plynx.python-list
    - kind: bool
      title: bool
      cls: plynx.plugins.resources.common.Raw
      icon: plynx.python-bool

  operations:
    - kind: basic-file
      title: File
      executor: plynx.plugins.executors.local.File
      icon: feathericons.file
      color: '#fff'
      is_static: true
      resources:
        - file
        - pdf
        - image
        - csv
        - tsv
        - json
        - executable
        - directory
        - cloud-storage
        - numpy-array
    - kind: basic-bash-jinja2-operation
      title: Basic BashJinja2
      executor: plynx.plugins.executors.local.BashJinja2
      icon: feathericons.terminal
      color: '#0f0'
      resources:
        - file
        - pdf
        - image
        - csv
        - tsv
        - json
        - executable
        - directory
        - cloud-storage
        - numpy-array
    - kind: basic-python-node-operation
      title: Basic Python
      executor: plynx.plugins.executors.local.PythonNode
      icon: plynx.python-logo-notext
      color: ''
      resources:
        - file
        - pdf
        - image
        - csv
        - tsv
        - json
        - executable
        - directory
        - cloud-storage
        - numpy-array
    - kind: python-code-operation
      title: Python Code Operation
      executor: plynx.plugins.executors.local.PythonNode
      icon: plynx.python-logo-notext
      color: ''
      resources:
        - int
        - str
        - dict
        - float
        - bool
    - kind: basic-dag-operation
      title: Composite Operation
      executor: plynx.plugins.executors.dag.DAG
      icon: feathericons.grid
      color: '#5ed1ff'
      operations:
        - basic-bash-jinja2-operation
        - basic-python-node-operation
        - basic-dag-operation
      resources:
        - file
        - pdf
        - image
        - csv
        - tsv
        - json
        - executable
        - directory
        - cloud-storage
        - numpy-array
    - kind: k8s-bash-jinja2-operation
      title: Kubernetes BashJinja2
      executor: plynx.plugins.executors.kubernetes.BashJinja2
      icon: plynx.kubernetes
      color: '#0f0'
      resources:
        - file
        - pdf
        - image
        - csv
        - tsv
        - json
        - executable
        - directory
        - cloud-storage
        - numpy-array
    - kind: k8s-python-node-operation
      title: Kubernetes Python
      executor: plynx.plugins.executors.kubernetes.PythonNode
      icon: plynx.kubernetes
      color: '#2196f3'
      resources:
        - file
        - pdf
        - image
        - csv
        - tsv
        - json
        - executable
        - directory
        - cloud-storage
        - numpy-array
  hubs:
    - kind: db-hub
      title: Database hub
      icon: feathericons.database
      cls: plynx.plugins.hubs.collection.CollectionHub
      args:
        operations:
          - basic-bash-jinja2-operation
          - basic-python-node-operation
          - basic-dag-operation
          - k8s-bash-jinja2-operation
          - k8s-python-node-operation
        collection: templates
    - kind: db-files-hub
      title: Files
      icon: feathericons.file
      cls: plynx.plugins.hubs.collection.CollectionHub
      args:
        operations:
          - basic-file
        collection: templates
    - kind: static-hub
      title: Static hub
      icon: feathericons.file
      cls: plynx.plugins.hubs.static_list.StaticListHub
      args:
        list_module: plynx.demo.COLLECTION
  workflows:
    - kind: basic-dag-workflow
      title: Basic DAG Workflow
      executor: plynx.plugins.executors.dag.DAG
      hubs:
        - db-hub
        - db-files-hub
    - kind: python-workflow
      title: Python Workflow
      executor: plynx.plugins.executors.python.dag.DAG
      hubs:
        - static-hub
        - db-hub

default_policies:
  - CAN_VIEW_OTHERS_OPERATIONS
  - CAN_VIEW_OTHERS_WORKFLOWS
  - CAN_VIEW_OPERATIONS
  - CAN_VIEW_WORKFLOWS
  - CAN_CREATE_OPERATIONS
  - CAN_CREATE_WORKFLOWS
  - CAN_MODIFY_OTHERS_WORKFLOWS
  - CAN_RUN_WORKFLOWS
